mujoco_server:
  ros__parameters:
    MujocoPlugins:
      names:
        - mujoco_ros2_control
      mujoco_ros2_control:
        type: mujoco_ros2_control::MujocoRos2ControlPlugin
        hardware:
          type: mujoco_ros_control/RobotHW
          control_period: 0.001
        params:
          namespace: ""
          robot_description_node: "robot_state_publisher"
          robot_description: "robot_description"

controller_manager:
    ros__parameters:
      update_rate: 1000
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      franka_robot_state_broadcaster:
        type: franka_robot_state_broadcaster/FrankaRobotStateBroadcaster
      franka_robot_model_broadcaster:
        type: franka_robot_state_broadcaster/FrankaRobotModelBroadcaster
      joint_impedance_example_controller:
        type: franka_example_controllers/JointImpedanceExampleController
      cartesian_impedance_example_controller:
        type: franka_example_controllers/CartesianImpedanceExampleController
      multi_mode_controller:
        type: multi_mode_controller/MultiModeController
franka_robot_state_broadcaster:
  ros__parameters:
    arm_id: panda
    frequency: 60
    
franka_robot_model_broadcaster:
  ros__parameters:
    arm_id: panda
    frequency: 60

joint_impedance_example_controller:
  ros__parameters:
    arm_id: panda
    k_gains:
      - 24.0
      - 24.0
      - 24.0
      - 24.0
      - 10.0
      - 6.0
      - 2.0
    d_gains:
      - 2.0
      - 2.0
      - 2.0
      - 1.0
      - 1.0
      - 1.0
      - 0.5

cartesian_impedance_example_controller:
  ros__parameters:
    arm_id: panda
  
multi_mode_controller:
  ros__parameters:
    arm_count: 1
    arm_1:
      arm_id: panda
    controllers: ["panda_joint_impedance_controller", "panda_cartesian_impedance_controller"]
    resources:
        panda_joint_impedance_controller: ["panda"]
        panda_cartesian_impedance_controller: ["panda"]
    start_controllers:
        names: ["panda_joint_impedance_controller"]
        resources:
            panda_joint_impedance_controller: ["panda"]