#### Request ####
string mission_id
---
#### Result ####

# Status of the tree
NodeStatus node_status
# result payload or error message
string return_message
---
#### Feedback ####

#This can be customized by the user
string message
