#### Request ####
string container_name
---
#### Result ####

# Status of the tree
NodeStatus node_status
# result payload or error message
string message
---
#### Feedback ####

#This can be customized by the user
string message
