controller_names:
  - dual_panda_arm_controller
  - panda_gripper_1
  - panda_gripper_2

dual_panda_arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: false
  joints:
    - mj_left_joint1
    - mj_left_joint2
    - mj_left_joint3
    - mj_left_joint4
    - mj_left_joint5
    - mj_left_joint6
    - mj_left_joint7
    - mj_right_joint1
    - mj_right_joint2
    - mj_right_joint3
    - mj_right_joint4
    - mj_right_joint5
    - mj_right_joint6
    - mj_right_joint7

panda_gripper_1:
    action_ns: gripper_1_action
    type: GripperCommand
    default: true
    joints:
      - mj_left_finger_joint1
      - mj_left_finger_joint2

panda_gripper_2:
    action_ns: gripper_2_action
    type: GripperCommand
    default: true
    joints:
      - mj_right_finger_joint1
      - mj_right_finger_joint2